## Generic Analysis
repos:

-   repo: local
    hooks:
    -   id: section-generic
        name: "[GENERIC ANALYSIS]"
        entry: pipenv --version
        language: system
        pass_filenames: false
        always_run: true

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        # check for invalidly formatted files
    -   id: check-yaml
    -   id: check-json

        # Git checks
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: detect-private-key

        # Python
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma

        # General quality checks
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
    -   id: end-of-file-fixer
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
    -   id: remove-tabs
        exclude: .*\.md$
    -   id: forbid-tabs
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    -   id: script-must-have-extension
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets

### Formatters

-   repo: local
    hooks:
    -   id: section-formatters
        name: "[FORMATTERS]"
        entry: pipenv --version
        language: system
        pass_filenames: false
        always_run: true

#### Python
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

### Specific Scanners

-   repo: local
    hooks:
    -   id: section-language-scanners
        name: "[SPECIFIC LANGUAGE SCANNERS]"
        entry: pipenv --version
        language: system
        pass_filenames: false
        always_run: true

#### Python
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args: ["-c", "bandit.yaml"]
-   repo: https://github.com/PyCQA/pylint
    rev: v2.15.10
    hooks:
    -   id: pylint
        args: [--rcfile=./.pylintrc]
        additional_dependencies:
        - .  # <-- that makes it install current project
        - flask
        - pytest
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        pass_filenames: false
        args: [--strict, flask_server, test, --implicit-reexport]
        additional_dependencies:
        - .  # <-- that makes it install current project
        - flask
        - pytest

#### Bash Scripts
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
    -   id: shellcheck

#### Markdown documents
-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.11
    hooks:
      - id: pymarkdown
        pass_filenames: false
        args:
          - --config
          - clean.json
          - scan
          - README.md
          - project_information.md
